
version: "3.1"
services:
  web:
    image: nginx:latest
    volumes:
      - ./devops/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:cached
    ports:
      - "8001:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: devops/Dockerfile
    container_name: cafe-fpm
    environment:
      CAFE_DATABASE_URL: 'mysql://cafe-user:cafe-pass@mysql:3306/cafe-db?serverVersion=5.7&charset=UTF8'
      XDEBUG_ENABLED: 1
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: cafe-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-cafe
      MYSQL_DATABASE: cafe-db
      MYSQL_USER: cafe-user
      MYSQL_PASSWORD: cafe-pass
    ports:
      - 3307:3306